webproj/src/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password-change"
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    url(
        r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
]

webproj/src/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("me/", views.ShowProfile.as_view(), name="show_self"),
    path("me/edit/", views.EditProfile.as_view(), name="edit_self"),
    path("<slug:slug>/", views.ShowProfile.as_view(), name="show"),
]

webproj/src/templates/_brandname.html
Devise Solutions

webproj/src/templates/_navbar.html
<div class="nav-links">  
  <a class="header-nav-link" href="{% url 'home' %}">Home</a>
  <a class="header-nav-link" href="{% url 'about' %}">About</a>
  <a class="header-nav-link btn-default header-nav-link.button" href="{% url 'accounts:login' %}">Log in</a>
  <a class="header-nav-link btn header-nav-link.button" href="{% url 'accounts:signup' %}">Sign up</a>
</div>

webproj/src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block container %}
	<div id="sec2" class="text-page">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h2>Meet Devise Solutions</h2>
					<p class="lead">These are the people behind the project!</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<div class="text-center"><img class="img-circle centered" src="{% static '/site/img/Jason.png' %}" alt="profile pic" style="max-height:220px;width:220px;"></div>
					<p class="heavy text-center">Jason Zhang <br> Co-Founder</p>
					<h2>Social Media and Marketing</h2>
					<p>Jason is our driven social media and applicant relations manager. He brings with him an intuitive skill for business systems.</p>
				</div>
				<div class="col-lg-4">
					<div class="text-center"><img class="img-circle centered" src="{% static 'site/img/Nick.png' %}" alt="profile pic" style="max-height:220px;width:220px;"></div>
					<p class="heavy text-center">Nick Foo <br> Co-Founder</p>
					<h2>Business Management and Operations</h2>
					<p>Nick Foo is our level-headed business relations manager. Nick is responsible for managing our business relations with the cool, calm, collectedness of the Antarctic Shelf - nothing shatters this man's confidence.</p>
				</div>
				<div class="col-lg-4">
					<div class="text-center"><img class="img-circle centered" src="{% static 'site/img/Albert.png' %}" alt="profile pic" style="max-height:220px;width:220px;"></div>
					<p class="heavy text-center">Albert Ferguson <br> Co-Founder </p>
					<h2>Lead Software Engineer and Analyst</h2>
					<p>Leading the charge into developing all the tech' required for this project, Albert is focussed and driven. Albert is reponsible for managing and developing mission critical software and processes. </p>
				</div>
				<div class="col-lg-4">
					<div class="text-center"><img class="img-circle centered" src="{% static 'site/img/Brendan.png' %}" alt="profile pic" style="max-height:220px;width:220px;"></div>
					<p class="heavy text-center">Brendan Hor <br> Co-Founder</p>
					<h2>Business Analysts and Growth</h2>
					<p>Brendan is our business model developer and inspires growth of the company at every step. His key focuss is on constantly improving our process. </p>
				</div>
				<div class="col-lg-4">
					<div class="text-center"><img class="img-circle centered" src="{% static 'site/img/' %}" alt="profile pic" style="max-height:220px;width:220px;"></div>
					<p class="heavy text-center">HIRING (kind of) Needed!</p>
					<h2>Graphics Designer and Lead Marketer</h2>
					<p>Logo and Business art design. We'll hire you, in the sense that you'll do work though - not that you'd get paid or anything...</p>
				</div>
			</div>
		</div>
	</div>

	<div id="sec3">
		<div class="container">
			<div class="row">
				<div id="map-outer" class="col-md-12">
					<div id="address" class="col-md-4">
						<h2>Our Location</h2>
						<address>
							<strong>Devise Solutions Ltd.</strong><br>
							Somewhere we can't afford<br>
							- Australia, Sydney<br>
							<abbr>P:</abbr> 0420698989
						</address>
					</div>
					<div id="map-container" class="col-md-8"></div>
				</div>
			</div>
		</div>
	</div>
{% endblock container %}

{% block scripts %}
	<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script>
	 function init_map() {
	 // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(-33.8692265, 151.2045018);
		 var mapOptions = {
					center: myLocation,
					zoom: 14
		 };
	 var marker = new google.maps.Marker({
		 position: myLocation,
		 title:"We are here"});
		 var map = new google.maps.Map(document.getElementById("map-container"),
																	 mapOptions);
	 marker.setMap(map);
	 }
	 google.maps.event.addDomListener(window, 'load', init_map);
	</script>
{% endblock scripts %}

webproj/src/templates/base - Working.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content ="width=device-width, initial-scale=1.">  
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="Albert Ferguson">

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    {% load static %}
    <link rel="shortcut icon" href="{% static 'site/img/devise_logo_main_.jpeg' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" type="text/css" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}
  </head>

  <body>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% block navbar %}
    
    <header class="header">
      <div class="wrapper">
        <div class="header-left">
          <a aria-current="page" class="logo header-brand-text" href="{% url 'home' %}"> <!-- old navbar-brand class -->
          {% block navbar-brand %}
              <img src="{% static 'site/img/D_symbol_link.png' %}">
              {% include "_brandname.html" %}
          {% endblock %}
          </a>
        </div> <!-- /header-left -->     
        {% block navbar-menu %}
        <div class="header-right">
          <nav class="header-nav">
            <div class="nav-links">  
              <a class="header-nav-link" href="{% url 'home' %}">Home</a>
              <a class="header-nav-link" href="{% url 'about' %}">About</a>
              <a class="header-nav-link btn-default header-nav-link.button" href="{% url 'accounts:login' %}">Log in</a>
              <a class="header-nav-link btn header-nav-link.button" href="{% url 'accounts:signup' %}">Sign up</a>
              {% block navbar-right %}
              {% endblock %} <!-- /.navbar-right -->
            </div>
          </div> <!--/.header-nav -->
        </div>
        {% endblock %} <!-- /.navbar-menu -->
      </div> <!-- /wrapper -->
    </header> <!-- /header-->
    
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <!-- Add social contact links for the page.-->
      <a id="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Devise Solutions Ltd. {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <!-- Logos are retrieved from the bootstrap source. -->
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

webproj/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content ="width=device-width, initial-scale=1.">  
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="Albert Ferguson">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    {% load static %}
    <link rel="shortcut icon" href="{% static 'site/img/FOM_test_logo.png' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" type="text/css" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}
  </head>

  <body>

  	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
             <img src="{% static 'site/img/FOM_test_logo.png' %}">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
            <div class="dropdown">
              <div>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
                {{ user.get_full_name|truncatechars:20 }}
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              </div>
            </div>
              {% endif %}
            {% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <!-- Add social contact links for the page.-->
      <a id="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Devise Solutions Ltd. {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <!-- Logos are retrieved from the bootstrap source. -->
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

webproj/src/templates/base_orig.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content ="width=device-width, initial-scale=1.">  
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="Albert Ferguson">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    {% load static %}
    <link rel="shortcut icon" href="{% static 'site/img/D_symbol_link.png' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" type="text/css" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}
  </head>

  <body>

  	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
             <img src="{% static 'site/img/D_symbol_link.png' %}">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <div class="dropdown">
                  <div>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
                    {{ user.get_full_name|truncatechars:20 }}
                    <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                  </div>
                </div>
              {% endif %}
            {% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <!-- Add social contact links for the page.-->
      <a id="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Devise Solutions Ltd. {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <!-- Logos are retrieved from the bootstrap source. -->
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

webproj/src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block styles %}
<link href="{% static 'site/css/main.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'site/css/home.css' %}" type="text/css" rel="stylesheet">
{% endblock styles %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign Up</a>
        </div>
      </div>
    </div>
  </div>

{% endblock splash %}


{% block container %}
  <div class="info-block">
    <div class="wrapper">
      <div class="info-header">
        <h2 class="info-title">Devise makes it easier to connect to jobs that matter to you and your skill set:</h2>
      </div>
      <div class="info-navs">
        <a style="transition-delay: 0.6s;" class="info-item" title="About" href="/about" >
          <div class="info-svg" alt="about"><!-- add image svg for about here --></div> 
          <h2>Read more</h2>
          <div class="info-content"><p>Find out about the team behind the project and what drives us</p></div>
        </a>
        <a class="info-item" title="FAQs" href="#" style="transition-delay: 0.6s;">
          <div class="info-svg" alt="faqs"><!-- add image svg for about here --></div> 
          <h2>Common Questions</h2>
          <div class="info-content"><p>Got questions? See here for the common ones</p></div>
        </a>
        <a class="info-item" title="Coming soon" href="#" style="transition-delay: 0.6s;">
          <div class="info-svg" alt="coming soon"><!-- add image svg for about here --></div> 
          <h2>See the preview what's next</h2>
          <div class="info-content"><p>What could it be?</p></div>
        </a>
      </div>
    </div>
  </div>
{% endblock %}


{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}